[project]
name = "tcc-g15"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "maliang[opt]>=3.1.5",
    "pystray>=0.19.5",
    "wmi>=1.5.1",
]
